### PR TITLE
Fix issue #101

### PR DESCRIPTION
**Pull request by AlisonLiii**
Fix issue #101 

Main changes:

- In **exception.py**, added a helper function _checkVariable_helper_ to check whether the variable is of the specified data type. The data could be list, dict, or str. If not, a TypeError will be raised. 
- Replaced all the three function calls (_checkStringVariable_, _checkDictionaryVariable_, _checkListVariable_) with the helper function _checkVariable_helper_ in other parts of the code.
- Deleted the definitions of the three functions mentioned above to avoid similar code blocks.

### CODE REVIEW

**Comment by AlisonLiii** [comment]
Could you please check whether it can work now? @GersonMontesinos  Thanks a lot!!!!

**Review by GersonMontesinos — CHANGES_REQUESTED** [review]
Did you know that this makes the exception.py file go from F to D in maintainability according to CodeClimate? Great idea, I still believe it can be improved, I recognize the effort of attempting to keep the same message but it's not that much of a requirement, that's just something to see on the terminal so whoever is debugging understands what's going on in case an Exception is raised. I attached a picture in which you can see the following: 
First, you can use the syntax `if-elif` for that case.
Last, you can reduce the amount of lines of code by a bit with the line 641! Test it yourself and let me know if you like the idea. If so, you can change these and make the PR again.

Thanks again @AlisonLiii for contributing!
issue 101_jiening

**Comment by AlisonLiii** [comment]
Thanks for the idea! It's great! I am about to change it. Just wondering, should I open a new pull request if I want to change the code?

**Comment by GersonMontesinos** [comment]
Yes please @AlisonLiii, make your changes on your local repository, push your changes and make the PR again. Let me know if you have any further questions.

**Comment by AlisonLiii** [comment]
Thanks! Will do

**Pull request closed without merging**
